### ISSUE TITLE
I would suggest .ng.html for extension

### ISSUE THREAD

**Issue by Urigo** [JNissi/meteor-ng-annotate#2]

**Comment by JNissi** [comment]
Hum, are you sure about .html? Shouldn't it be .ng.js?

**Comment by Urigo** [comment]
too late :)
https://github.com/Urigo/angular-meteor/commit/29d4cf88894598db930e912ded6c3f0b8a88a5f0

**Comment by JNissi** [comment]
Nice. I think I'll deprecate this one then =D

**Comment by Urigo** [comment]
:)
